/**
 * Country list with continent mapping + continent options for the profile
 * Country / Continent dropdowns. Kept here so the data can be edited without
 * touching UI. `COUNTRIES` items carry an extra `continent` field but remain
 * assignable to the shared `Option` type (they have `value` + `label`).
 */
import type { Option } from "@/lib/startup-profile-options";

export interface Country {
  value: string; // ISO 3166-1 alpha-2 code
  label: string;
  continent: string; // matches a CONTINENTS value
}

export const CONTINENTS: Option[] = [
  { value: "africa", label: "Africa" },
  { value: "antarctica", label: "Antarctica" },
  { value: "asia", label: "Asia" },
  { value: "europe", label: "Europe" },
  { value: "north_america", label: "North America" },
  { value: "oceania", label: "Oceania" },
  { value: "south_america", label: "South America" },
];

export const COUNTRIES: Country[] = [
  { value: "AF", label: "Afghanistan", continent: "asia" },
  { value: "AL", label: "Albania", continent: "europe" },
  { value: "DZ", label: "Algeria", continent: "africa" },
  { value: "AD", label: "Andorra", continent: "europe" },
  { value: "AO", label: "Angola", continent: "africa" },
  { value: "AG", label: "Antigua and Barbuda", continent: "north_america" },
  { value: "AR", label: "Argentina", continent: "south_america" },
  { value: "AM", label: "Armenia", continent: "asia" },
  { value: "AU", label: "Australia", continent: "oceania" },
  { value: "AT", label: "Austria", continent: "europe" },
  { value: "AZ", label: "Azerbaijan", continent: "asia" },
  { value: "BS", label: "Bahamas", continent: "north_america" },
  { value: "BH", label: "Bahrain", continent: "asia" },
  { value: "BD", label: "Bangladesh", continent: "asia" },
  { value: "BB", label: "Barbados", continent: "north_america" },
  { value: "BY", label: "Belarus", continent: "europe" },
  { value: "BE", label: "Belgium", continent: "europe" },
  { value: "BZ", label: "Belize", continent: "north_america" },
  { value: "BJ", label: "Benin", continent: "africa" },
  { value: "BT", label: "Bhutan", continent: "asia" },
  { value: "BO", label: "Bolivia", continent: "south_america" },
  { value: "BA", label: "Bosnia and Herzegovina", continent: "europe" },
  { value: "BW", label: "Botswana", continent: "africa" },
  { value: "BR", label: "Brazil", continent: "south_america" },
  { value: "BN", label: "Brunei", continent: "asia" },
  { value: "BG", label: "Bulgaria", continent: "europe" },
  { value: "BF", label: "Burkina Faso", continent: "africa" },
  { value: "BI", label: "Burundi", continent: "africa" },
  { value: "CV", label: "Cabo Verde", continent: "africa" },
  { value: "KH", label: "Cambodia", continent: "asia" },
  { value: "CM", label: "Cameroon", continent: "africa" },
  { value: "CA", label: "Canada", continent: "north_america" },
  { value: "CF", label: "Central African Republic", continent: "africa" },
  { value: "TD", label: "Chad", continent: "africa" },
  { value: "CL", label: "Chile", continent: "south_america" },
  { value: "CN", label: "China", continent: "asia" },
  { value: "CO", label: "Colombia", continent: "south_america" },
  { value: "KM", label: "Comoros", continent: "africa" },
  { value: "CG", label: "Congo (Republic)", continent: "africa" },
  { value: "CD", label: "Congo (DRC)", continent: "africa" },
  { value: "CR", label: "Costa Rica", continent: "north_america" },
  { value: "CI", label: "Côte d'Ivoire", continent: "africa" },
  { value: "HR", label: "Croatia", continent: "europe" },
  { value: "CU", label: "Cuba", continent: "north_america" },
  { value: "CY", label: "Cyprus", continent: "asia" },
  { value: "CZ", label: "Czechia", continent: "europe" },
  { value: "DK", label: "Denmark", continent: "europe" },
  { value: "DJ", label: "Djibouti", continent: "africa" },
  { value: "DM", label: "Dominica", continent: "north_america" },
  { value: "DO", label: "Dominican Republic", continent: "north_america" },
  { value: "EC", label: "Ecuador", continent: "south_america" },
  { value: "EG", label: "Egypt", continent: "africa" },
  { value: "SV", label: "El Salvador", continent: "north_america" },
  { value: "GQ", label: "Equatorial Guinea", continent: "africa" },
  { value: "ER", label: "Eritrea", continent: "africa" },
  { value: "EE", label: "Estonia", continent: "europe" },
  { value: "SZ", label: "Eswatini", continent: "africa" },
  { value: "ET", label: "Ethiopia", continent: "africa" },
  { value: "FJ", label: "Fiji", continent: "oceania" },
  { value: "FI", label: "Finland", continent: "europe" },
  { value: "FR", label: "France", continent: "europe" },
  { value: "GA", label: "Gabon", continent: "africa" },
  { value: "GM", label: "Gambia", continent: "africa" },
  { value: "GE", label: "Georgia", continent: "asia" },
  { value: "DE", label: "Germany", continent: "europe" },
  { value: "GH", label: "Ghana", continent: "africa" },
  { value: "GR", label: "Greece", continent: "europe" },
  { value: "GD", label: "Grenada", continent: "north_america" },
  { value: "GT", label: "Guatemala", continent: "north_america" },
  { value: "GN", label: "Guinea", continent: "africa" },
  { value: "GW", label: "Guinea-Bissau", continent: "africa" },
  { value: "GY", label: "Guyana", continent: "south_america" },
  { value: "HT", label: "Haiti", continent: "north_america" },
  { value: "HN", label: "Honduras", continent: "north_america" },
  { value: "HU", label: "Hungary", continent: "europe" },
  { value: "IS", label: "Iceland", continent: "europe" },
  { value: "IN", label: "India", continent: "asia" },
  { value: "ID", label: "Indonesia", continent: "asia" },
  { value: "IR", label: "Iran", continent: "asia" },
  { value: "IQ", label: "Iraq", continent: "asia" },
  { value: "IE", label: "Ireland", continent: "europe" },
  { value: "IL", label: "Israel", continent: "asia" },
  { value: "IT", label: "Italy", continent: "europe" },
  { value: "JM", label: "Jamaica", continent: "north_america" },
  { value: "JP", label: "Japan", continent: "asia" },
  { value: "JO", label: "Jordan", continent: "asia" },
  { value: "KZ", label: "Kazakhstan", continent: "asia" },
  { value: "KE", label: "Kenya", continent: "africa" },
  { value: "KI", label: "Kiribati", continent: "oceania" },
  { value: "KW", label: "Kuwait", continent: "asia" },
  { value: "KG", label: "Kyrgyzstan", continent: "asia" },
  { value: "LA", label: "Laos", continent: "asia" },
  { value: "LV", label: "Latvia", continent: "europe" },
  { value: "LB", label: "Lebanon", continent: "asia" },
  { value: "LS", label: "Lesotho", continent: "africa" },
  { value: "LR", label: "Liberia", continent: "africa" },
  { value: "LY", label: "Libya", continent: "africa" },
  { value: "LI", label: "Liechtenstein", continent: "europe" },
  { value: "LT", label: "Lithuania", continent: "europe" },
  { value: "LU", label: "Luxembourg", continent: "europe" },
  { value: "MG", label: "Madagascar", continent: "africa" },
  { value: "MW", label: "Malawi", continent: "africa" },
  { value: "MY", label: "Malaysia", continent: "asia" },
  { value: "MV", label: "Maldives", continent: "asia" },
  { value: "ML", label: "Mali", continent: "africa" },
  { value: "MT", label: "Malta", continent: "europe" },
  { value: "MH", label: "Marshall Islands", continent: "oceania" },
  { value: "MR", label: "Mauritania", continent: "africa" },
  { value: "MU", label: "Mauritius", continent: "africa" },
  { value: "MX", label: "Mexico", continent: "north_america" },
  { value: "FM", label: "Micronesia", continent: "oceania" },
  { value: "MD", label: "Moldova", continent: "europe" },
  { value: "MC", label: "Monaco", continent: "europe" },
  { value: "MN", label: "Mongolia", continent: "asia" },
  { value: "ME", label: "Montenegro", continent: "europe" },
  { value: "MA", label: "Morocco", continent: "africa" },
  { value: "MZ", label: "Mozambique", continent: "africa" },
  { value: "MM", label: "Myanmar", continent: "asia" },
  { value: "NA", label: "Namibia", continent: "africa" },
  { value: "NR", label: "Nauru", continent: "oceania" },
  { value: "NP", label: "Nepal", continent: "asia" },
  { value: "NL", label: "Netherlands", continent: "europe" },
  { value: "NZ", label: "New Zealand", continent: "oceania" },
  { value: "NI", label: "Nicaragua", continent: "north_america" },
  { value: "NE", label: "Niger", continent: "africa" },
  { value: "NG", label: "Nigeria", continent: "africa" },
  { value: "KP", label: "North Korea", continent: "asia" },
  { value: "MK", label: "North Macedonia", continent: "europe" },
  { value: "NO", label: "Norway", continent: "europe" },
  { value: "OM", label: "Oman", continent: "asia" },
  { value: "PK", label: "Pakistan", continent: "asia" },
  { value: "PW", label: "Palau", continent: "oceania" },
  { value: "PA", label: "Panama", continent: "north_america" },
  { value: "PG", label: "Papua New Guinea", continent: "oceania" },
  { value: "PY", label: "Paraguay", continent: "south_america" },
  { value: "PE", label: "Peru", continent: "south_america" },
  { value: "PH", label: "Philippines", continent: "asia" },
  { value: "PL", label: "Poland", continent: "europe" },
  { value: "PT", label: "Portugal", continent: "europe" },
  { value: "QA", label: "Qatar", continent: "asia" },
  { value: "RO", label: "Romania", continent: "europe" },
  { value: "RU", label: "Russia", continent: "europe" },
  { value: "RW", label: "Rwanda", continent: "africa" },
  { value: "KN", label: "Saint Kitts and Nevis", continent: "north_america" },
  { value: "LC", label: "Saint Lucia", continent: "north_america" },
  { value: "VC", label: "Saint Vincent and the Grenadines", continent: "north_america" },
  { value: "WS", label: "Samoa", continent: "oceania" },
  { value: "SM", label: "San Marino", continent: "europe" },
  { value: "ST", label: "São Tomé and Príncipe", continent: "africa" },
  { value: "SA", label: "Saudi Arabia", continent: "asia" },
  { value: "SN", label: "Senegal", continent: "africa" },
  { value: "RS", label: "Serbia", continent: "europe" },
  { value: "SC", label: "Seychelles", continent: "africa" },
  { value: "SL", label: "Sierra Leone", continent: "africa" },
  { value: "SG", label: "Singapore", continent: "asia" },
  { value: "SK", label: "Slovakia", continent: "europe" },
  { value: "SI", label: "Slovenia", continent: "europe" },
  { value: "SB", label: "Solomon Islands", continent: "oceania" },
  { value: "SO", label: "Somalia", continent: "africa" },
  { value: "ZA", label: "South Africa", continent: "africa" },
  { value: "KR", label: "South Korea", continent: "asia" },
  { value: "SS", label: "South Sudan", continent: "africa" },
  { value: "ES", label: "Spain", continent: "europe" },
  { value: "LK", label: "Sri Lanka", continent: "asia" },
  { value: "SD", label: "Sudan", continent: "africa" },
  { value: "SR", label: "Suriname", continent: "south_america" },
  { value: "SE", label: "Sweden", continent: "europe" },
  { value: "CH", label: "Switzerland", continent: "europe" },
  { value: "SY", label: "Syria", continent: "asia" },
  { value: "TW", label: "Taiwan", continent: "asia" },
  { value: "TJ", label: "Tajikistan", continent: "asia" },
  { value: "TZ", label: "Tanzania", continent: "africa" },
  { value: "TH", label: "Thailand", continent: "asia" },
  { value: "TL", label: "Timor-Leste", continent: "asia" },
  { value: "TG", label: "Togo", continent: "africa" },
  { value: "TO", label: "Tonga", continent: "oceania" },
  { value: "TT", label: "Trinidad and Tobago", continent: "north_america" },
  { value: "TN", label: "Tunisia", continent: "africa" },
  { value: "TR", label: "Turkey", continent: "asia" },
  { value: "TM", label: "Turkmenistan", continent: "asia" },
  { value: "TV", label: "Tuvalu", continent: "oceania" },
  { value: "UG", label: "Uganda", continent: "africa" },
  { value: "UA", label: "Ukraine", continent: "europe" },
  { value: "AE", label: "United Arab Emirates", continent: "asia" },
  { value: "GB", label: "United Kingdom", continent: "europe" },
  { value: "US", label: "United States", continent: "north_america" },
  { value: "UY", label: "Uruguay", continent: "south_america" },
  { value: "UZ", label: "Uzbekistan", continent: "asia" },
  { value: "VU", label: "Vanuatu", continent: "oceania" },
  { value: "VA", label: "Vatican City", continent: "europe" },
  { value: "VE", label: "Venezuela", continent: "south_america" },
  { value: "VN", label: "Vietnam", continent: "asia" },
  { value: "YE", label: "Yemen", continent: "asia" },
  { value: "ZM", label: "Zambia", continent: "africa" },
  { value: "ZW", label: "Zimbabwe", continent: "africa" },
];

/** Continent value for a given country value ("" if unknown). */
export function continentForCountry(value: string): string {
  return COUNTRIES.find((c) => c.value === value)?.continent ?? "";
}
